repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: debug-statements
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        name: Autocode formatter (black)
  - repo: local
    hooks:
      - id: tests
        name: Run pytest
        entry: pipenv run pytest
        language: system
        # types: [python]
        require_serial: true
        pass_filenames: false
        # stages: [push]
