version: "3"
services:
  postgres:
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=ahs_admin
      - POSTGRES_PASSWORD=gfhandel
      - POSTGRES_DB=americanhandelsociety_postgres
  app:
    build: .
    # Allow container to be attached to, e.g., to access the pdb shell
    stdin_open: true
    tty: true
    ports:
      - 8000:8000
    depends_on:
      - postgres
    volumes:
      # Mount the development directory as a volume into the container, so
      # Docker automatically recognizes your changes.
      - .:/app
