# Generated by Django 3.1.7 on 2021-05-01 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("americanhandelsociety_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                verbose_name="active",
            ),
        ),
    ]
