# Generated by Django 3.1.9 on 2021-11-11 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("americanhandelsociety_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="accepts_privacy_policy",
            field=models.BooleanField(default=False),
        ),
    ]
