# Generated by Django 3.1.9 on 2021-11-29 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("americanhandelsociety_app", "0002_member_accepts_privacy_policy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="membership_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("REGULAR", "40.00"),
                    ("STUDENT", "20.00"),
                    ("RETIRED", "20.00"),
                    ("JOINT", "50.00"),
                    ("RINALDO_CIRCLE", "75.00"),
                    ("CLEOPATRA_CIRCLE", "125.00"),
                    ("THEODORA_CIRCLE", "250.00"),
                    ("MESSIAH_CIRCLE", "500.00"),
                ],
                max_length=16,
            ),
        ),
    ]
