# Generated by Django 3.1.9 on 2022-04-16 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("americanhandelsociety_app", "0003_revise_membership_rates"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="last_updated",
            field=models.DateTimeField(auto_now=True, null=True, default=None),
        ),
    ]
