# Generated by Django 4.0 on 2023-01-05 01:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("americanhandelsociety_app", "0005_alter_member_last_updated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="date_of_last_membership_payment",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
