# Generated by Django 4.0 on 2023-03-19 01:11

from django.db import migrations, models
from django_add_default_value import AddDefaultValue


class Migration(migrations.Migration):

    dependencies = [
        (
            "americanhandelsociety_app",
            "0006_alter_member_date_of_last_membership_payment",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="is_member_via_other_organization",
            field=models.BooleanField(
                default=False,
                help_text="Denotes if the member pays dues through a 'sister' organization, such as the Georg-Friedrich-Händel-Gesellschaft.",
            ),
        ),
        AddDefaultValue(
            model_name="member", name="is_member_via_other_organization", value=False
        ),
    ]
