# Generated by Django 4.0 on 2023-10-09 15:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("americanhandelsociety_app", "0007_member_is_member_via_other_organization"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="contact_preference",
            field=models.CharField(
                choices=[("PRINT", "Print"), ("EMAIL", "Email"), ("BOTH", "Both")],
                max_length=5,
            ),
        ),
    ]
