# Generated by Django 4.0 on 2023-12-18 14:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("americanhandelsociety_app", "0008_alter_member_contact_preference"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="can_showcase_membership_or_donation_data",
            field=models.BooleanField(
                default=False,
                help_text="Denotes if the AHS can showcase the member for being in a high membership 'tier' or contributing a donation to the society.",
            ),
        ),
    ]
